import { ElementRef, OnDestroy, TemplateRef } from '@angular/core';
import { DomHandler } from '../dom/domhandler';
export declare class PickList implements OnDestroy {
    private el;
    private domHandler;
    source: any[];
    target: any[];
    sourceHeader: string;
    targetHeader: string;
    responsive: boolean;
    style: string;
    styleClass: string;
    sourceStyle: string;
    targetStyle: string;
    itemTemplate: TemplateRef<any>;
    constructor(el: ElementRef, domHandler: DomHandler);
    onMouseover(event: any): void;
    onMouseout(event: any): void;
    onClick(event: any): void;
    findListItem(element: any): any;
    onItemClick(event: any, item: any): void;
    moveUp(listElement: any, list: any): void;
    moveTop(listElement: any, list: any): void;
    moveDown(listElement: any, list: any): void;
    moveBottom(listElement: any, list: any): void;
    moveRight(sourceListElement: any): void;
    moveAllRight(): void;
    moveLeft(targetListElement: any): void;
    moveAllLeft(): void;
    getListElements(listElement: any): any;
    getSelectedListElements(listElement: any): any[];
    ngOnDestroy(): void;
}
