import { ElementRef, AfterViewChecked, EventEmitter, TemplateRef, IterableDiffers } from '@angular/core';
import { SelectItem } from '../api/selectitem';
import { DomHandler } from '../dom/domhandler';
export declare class Listbox implements AfterViewChecked {
    private el;
    private domHandler;
    options: SelectItem[];
    multiple: boolean;
    style: string;
    styleClass: string;
    disabled: string;
    valueChange: EventEmitter<any>;
    onChange: EventEmitter<any>;
    itemTemplate: TemplateRef<any>;
    _value: any;
    differ: any;
    valueChanged: boolean;
    value: any;
    constructor(el: ElementRef, domHandler: DomHandler, differs: IterableDiffers);
    ngDoCheck(): void;
    ngAfterViewChecked(): void;
    preselect(): void;
    unselectAll(items: NodeList[]): void;
    onMouseover(event: any): void;
    onMouseout(event: any): void;
    onClick(event: any): void;
    onItemClick(event: any, item: any): void;
    unselectSiblings(item: any): void;
    findListItem(element: any): any;
}
