import { ElementRef, OnInit, OnDestroy, EventEmitter, QueryList, Renderer } from '@angular/core';
import { SplitButtonItem } from './splitbuttonitem';
import { DomHandler } from '../dom/domhandler';
export declare class SplitButton implements OnInit, OnDestroy {
    private el;
    private domHandler;
    private renderer;
    icon: string;
    iconPos: string;
    label: string;
    onClick: EventEmitter<any>;
    style: string;
    styleClass: string;
    menuStyle: string;
    menuStyleClass: string;
    items: QueryList<SplitButtonItem>;
    private hoverDefaultBtn;
    private focusDefaultBtn;
    private activeDefaultBtn;
    private hoverDropdown;
    private focusDropdown;
    private activeDropdown;
    private hoveredItem;
    private menuVisible;
    private documentClickListener;
    constructor(el: ElementRef, domHandler: DomHandler, renderer: Renderer);
    ngOnInit(): void;
    onDefaultButtonClick(event: any): void;
    onDropdownClick(event: any, menu: any, defaultbtn: any): void;
    onItemClick(event: any, item: SplitButtonItem): void;
    ngOnDestroy(): void;
}
